[package]
name = "carbon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
gltf = "1"
bytes = "1.1.0"
thiserror = "1.0"
image = "0.24"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
winit = "0.26"
glam = "0.20.5"